version: "3"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - webhook-relay

  webhook-relay-service:
    image: ghcr.io/traewelldroid/webhookrelayservice:dev
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - webhook-relay

networks:
  webhook-relay:
    driver: bridge

volumes:
  dbdata:
    driver: local
